In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
#reading data set
dataset=pd.read_csv("practiceDataset.csv")
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
dataset.shape #it contains 81 columns and 1460 rows

(1460, 81)

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [5]:
dataset.columns[dataset.isna().any()]  #this all columns contains "Nan" values that means missing values

Index(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence',
       'MiscFeature'],
      dtype='object')

In [6]:
#let us take few columnsand predict the saleprice
df=dataset[['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'HouseStyle', 'OverallQual', 'OverallCond','SalePrice']]
df

,MSSubClass,MSZoning,LotFrontage,LotArea,HouseStyle,OverallQual,OverallCond,SalePrice
0,60,RL,65.0,8450,2Story,7,5,208500
1,20,RL,80.0,9600,1Story,6,8,181500
2,60,RL,68.0,11250,2Story,7,5,223500
3,70,RL,60.0,9550,2Story,7,5,140000
4,60,RL,84.0,14260,2Story,8,5,250000
...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,2Story,6,5,175000
1456,20,RL,85.0,13175,1Story,6,6,210000
1457,70,RL,66.0,9042,2Story,7,9,266500
1458,20,RL,68.0,9717,1Story,5,6,142125
1459,20,RL,75.0,9937,1Story,5,6,147500

In [7]:
#from the above dataset we need to predict the saleprice using indeependent variable
#finding missing values columns
df.columns[df.isna().any()]

Index(['LotFrontage'], dtype='object')

In [8]:
#we can observe that LotFrontage contains missing value so that we neeed to handle it by replace with mean of that colums
df.LotFrontage=df.LotFrontage.fillna(df.LotFrontage.mean())
df

C:\Users\tumat\AppData\Local\Temp\ipykernel_10332\243796645.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.LotFrontage=df.LotFrontage.fillna(df.LotFrontage.mean())

,MSSubClass,MSZoning,LotFrontage,LotArea,HouseStyle,OverallQual,OverallCond,SalePrice
0,60,RL,65.0,8450,2Story,7,5,208500
1,20,RL,80.0,9600,1Story,6,8,181500
2,60,RL,68.0,11250,2Story,7,5,223500
3,70,RL,60.0,9550,2Story,7,5,140000
4,60,RL,84.0,14260,2Story,8,5,250000
...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,2Story,6,5,175000
1456,20,RL,85.0,13175,1Story,6,6,210000
1457,70,RL,66.0,9042,2Story,7,9,266500
1458,20,RL,68.0,9717,1Story,5,6,142125
1459,20,RL,75.0,9937,1Story,5,6,147500

In [9]:
df.isna().count() #there is no missing values in the df dataset

MSSubClass     1460
MSZoning       1460
LotFrontage    1460
LotArea        1460
HouseStyle     1460
OverallQual    1460
OverallCond    1460
SalePrice      1460
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   MSZoning     1460 non-null   object
 2   LotFrontage  1460 non-null   float64
 3   LotArea      1460 non-null   int64
 4   HouseStyle   1460 non-null   object
 5   OverallQual  1460 non-null   int64
 6   OverallCond  1460 non-null   int64
 7   SalePrice    1460 non-null   int64
dtypes: float64(1), int64(5), object(2)
memory usage: 91.4+ KB

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.MSZoning=le.fit_transform(df.MSZoning)
df.HouseStyle=le.fit_transform(df.HouseStyle)

C:\Users\tumat\AppData\Local\Temp\ipykernel_10332\2372082725.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.MSZoning=le.fit_transform(df.MSZoning)
C:\Users\tumat\AppData\Local\Temp\ipykernel_10332\2372082725.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.HouseStyle=le.fit_transform(df.HouseStyle)

In [12]:
#independent and dependent variables
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x,y

(      MSSubClass  MSZoning  LotFrontage  LotArea  HouseStyle  OverallQual  \
 0             60         3         65.0     8450           5            7
 1             20         3         80.0     9600           2            6
 2             60         3         68.0    11250           5            7
 3             70         3         60.0     9550           5            7
 4             60         3         84.0    14260           5            8
 ...          ...       ...          ...      ...         ...          ...
 1455          60         3         62.0     7917           5            6
 1456          20         3         85.0    13175           2            6
 1457          70         3         66.0     9042           5            7
 1458          20         3         68.0     9717           2            5
 1459          20         3         75.0     9937           2            5

       OverallCond
 0               5
 1               8
 2               5
 3               5
 4               5
 ...           ...
 1455            5
 1456            6
 1457            9
 1458            6
 1459            6

 [1460 rows x 7 columns],
 0       208500
 1       181500
 2       223500
 3       140000
 4       250000
          ...
 1455    175000
 1456    210000
 1457    266500
 1458    142125
 1459    147500
 Name: SalePrice, Length: 1460, dtype: int64)

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [18]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [19]:
model.predict(x_test)

array([227082.51991614, 142498.95109856, 123441.95567229, 237659.34983903,
        91062.54945603, 114062.62777963, 196235.32809849, 226659.48760274,
       258991.99383851,  41019.92190548, 276781.49946097, 220494.61967555,
        67544.91799287, 363917.56531698,  83361.23017912,  74115.72140452,
       233471.39085878, 138203.88777602, 155099.56337881,  96621.29524247,
       130247.40744537, 147873.13966916, 121651.05338124, 181007.12803805,
       119875.65107084, 167684.68992645, 225416.72970229, 199046.32380044,
       156200.63656788, 135790.92631665,  88969.41264981,  90260.29705395,
       272586.0722679 , 174576.90354225, 177631.87076786, 268634.58189884,
       221727.14334531, 165154.08600226, 180965.21207485, 232598.30390282,
        91184.94113516, 225416.72970229, 269767.71563802, 216821.14169672,
       186544.51177625, 109269.31978139, 221263.49209093, 266743.35386137,
       137024.58433307, 177178.44513163,  87965.67676024, 128684.2281895 ,
       226044.86228802, 176969.2975    , 181937.61003942,  93042.70468458,
       179045.18645786, 221059.60334044, 232794.03855888, 184764.178725  ,
       182396.53674693, 271940.6732961 , 187135.18721341, 173189.13227222,
       269663.57217995, 223406.28611304, 179175.23786155, 268296.50426944,
       266301.68596393, 210418.18145646, 220576.49551001, 231596.16872129,
       233097.3813752 , 148628.21864159, 108269.98530673,  64873.74217019,
       228699.94730942, 229567.88592773, 271347.01676376, 126261.01837168,
       246833.81944528, 229446.28388159, 181754.17333671, 233479.97659612,
       196115.74739187, 125547.38688484, 136975.50960143,  26427.6227363 ,
       122876.77634519, 268974.97290647, 267788.27897262, 189881.84594571,
       221016.76625275, 287012.54000424, 170288.27480181, 228113.00421213,
       199379.73512173, 205962.76567953, 187978.78963556, 220811.53764307,
       224272.67706156, 177362.86174428, 224991.76371133, 181924.14695471,
       268646.17357344, 174732.69616877, 218034.94173533, 261660.45602858,
       161252.79654863, 157524.70657482, 270430.64425506, 112261.1068931 ,
       188568.48301044, 133676.04821054, 177889.77511267, 213547.86283287,
       147756.76093887, 145121.93906971,  88966.40445248, 123497.62417743,
       231384.82593923,  95599.39579163,  63659.39380618, 140584.42148408,
       134310.94269645, 178600.62596269,  76845.9684072 , 122116.14064111,
       124144.30701364, 267727.70671451, 267130.85405508, 162441.69167782,
        89815.94925767, 272543.10722179,  51941.0926081 , 113982.92056818,
       258534.2968388 , 295718.6631294 , 128550.08960021, 216242.48005966,
       198387.58408867, 156077.60264378, 148264.93446972,  99192.08063351,
       122199.31561241, 272543.10722179, 184338.97038237, 230658.40996996,
       314148.94260867, 119296.10289075, 203240.21435941,  74227.50319163,
        78736.86789504, 183745.65626484, 190802.02345292, 213354.53392119,
       183054.36107744, 312192.23126461,  53200.40954106, 218050.85265362,
       211792.15870004, 245514.26065839, 178487.86110285, 169502.41548203,
        95783.33816275, 130588.79217845, 179063.72190942, 209519.15257233,
       101816.26360132, 188813.81414715, 178528.81481498,  96105.62904204,
       174535.72465516, 148873.3007619 , 179871.96730491, 182679.84842953,
       124622.92299953, 239006.23738169, 172742.20163129, 126427.90657604,
       274208.34612408, 177270.19494179, 140925.21813051, 134357.11730117,
       190235.05783444, 127724.02290847, 232144.20184857, 135034.54573967,
       130751.9533075 , 223207.91661116, 155175.44621987,  79154.92166597,
       352450.20864554, 227464.83366642, 136804.00863064, 193906.81607294,
       131120.21273754, 176558.06145814, 269369.83215005, 221855.48855685,
       135281.76138238, 116471.72464182,  90859.01605471, 234188.65357387,
       222724.46947862, 233222.18697474,  97216.87387597, 365490.46581312,
       135727.84351787, 179199.94054359, 180534.95930747, 135041.93428079,
       223892.02845914, 139107.15391706, 155099.56337881,  73483.21581107,
       265995.13034265, 136849.8720942 , 125979.13751485, 279209.29142937,
       188647.89043937, 149135.54976213, 143045.31776292, 265673.97433882,
       229145.41356045, 118582.58755335, 269159.31846196, 173778.84332431,
        48026.88711326, 115026.12298519, 277934.10533799, 287753.58608642,
        83971.04471982, 155084.87637732, 131517.04344169, 129552.9622318 ,
       182978.69347367, 206252.14179126, 282909.85772773, 162441.69167782,
       272543.10722179, 180779.09778795, 261150.05412544, 257384.12759278,
       324194.14879755, 138579.64578004, 263298.97331089, 283773.42021376,
        89333.72097315, 228529.88750789, 154635.06174628, 223286.15384059,
       175767.62442051, 181701.13600398, 138377.06249652, 133061.06048909,
       225710.91956511, 207631.06353345, 228244.79240276, 145036.67417453,
       312747.20253353, 225153.16810776,  85025.68414132, 175250.20649603,
       136589.89638082, 193842.49962674, 134937.11172055, 158255.55337068,
       167202.27180041, 178092.07903048,  85300.57108872, 191044.19181372,
       138627.08918679, 224070.48679683, 224206.68823352,  92289.79628704,
       155297.28615562, 119362.59624369, 160328.15246742, 136572.50740014,
       143583.60452642, 167161.47348166, 190802.02345292, 136331.89753838,
       115445.65375372, 125479.73236626, 310350.42579144, 190804.90274101,
       133290.01447924, 134295.99253145, 186740.55167235, 194168.08550804,
       138299.95573868, 273342.23963538, 226426.44687381, 234535.55362265,
        94445.3393568 , 269990.46849402, 183469.30636873, 361088.96888771,
       150047.25142107, 269420.01273849, 115572.17778672, 133851.00265343,
       277221.51890109, 316302.50706354,  87187.90269398, 130272.96750421,
       133465.28351726, 317457.30809099,  71242.89262033, 182137.64492948,
       183131.58147295, 156077.60264378, 224762.13324724, 118982.00823075,
        -5607.82808998, 184211.52571405, 128635.85139829, 127919.08342464,
       118928.33001533, 178627.0398312 , 261894.39319489, 275646.87495327,
        93085.31142396, 216370.2332986 ,  53130.10271621, 115482.75118998,
         1198.15003889, 182448.09387218, 282952.44159051, 310750.23621024,
       129953.53034458, 115094.47480748, 190159.17499338, 129034.02151231,
        65753.35406921, 152973.36292876, 177832.60867074, 119567.54926756,
       125290.64460505, 222499.30688215, 195046.21153574, 216242.48005966,
        73582.37184436, 160469.49792588, 209699.37508639, 227425.53387375,
       172250.97128715, 268591.63428033, 135866.65146892, 132415.49039698,
       191233.27361794, 262669.17019335, 218481.99511712, 122231.27773323,
       148277.61911409, 188474.12058683, 270853.26644632, 125335.44518749,
       293934.34120331, 130004.02642911, 191755.56251529, 144235.04377361,
       119296.10289075])

In [20]:
x

,MSSubClass,MSZoning,LotFrontage,LotArea,HouseStyle,OverallQual,OverallCond
0,60,3,65.0,8450,5,7,5
1,20,3,80.0,9600,2,6,8
2,60,3,68.0,11250,5,7,5
3,70,3,60.0,9550,5,7,5
4,60,3,84.0,14260,5,8,5
...,...,...,...,...,...,...,...
1455,60,3,62.0,7917,5,6,5
1456,20,3,85.0,13175,2,6,6
1457,70,3,66.0,9042,5,7,9
1458,20,3,68.0,9717,2,5,6
1459,20,3,75.0,9937,2,5,6

In [23]:
data=[[60,3,65.0,8450,5,7,5]]
print("The sale price is ",model.predict(data))

The sale price is  [219823.33685048]

C:\Users\tumat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [24]:
data=[[20,3,80.0,9600,2,6,8]]
model.predict(data)

C:\Users\tumat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([179175.23786155])